CapstoneDesign24-GQ/FE

cd-gq/package-lock.json, cd-gq/package.json, cd-gq/src/App.js, cd-gq/src/components/BlockButton.js, cd-gq/src/pages/Detail.js, cd-gq/src/pages/Home.js, cd-gq/src/pages/Sitemap.js, cd-gq/src/pages/main.js, cd-gq/src/routes.js
setting: 각 페이지 라우터 설정 / fix: orange속성 적용안되는 부분 수정 적용
[preview]
=> setting: 각 페이지 라우터 설정 / fix: orange속성 적용안되는 부분 수정 적용

cd-gq/src/styles/global.js, cd-gq/src/styles/theme.js
=> add: components / pr tamplet check

cd-gq/src/App.js, cd-gq/src/index.js, cd-gq/src/styles/Mobile.js
- Global 설정 완료 : Global.js와 Mobile.js를 사용
> Global.js : 태그 속성 reset
> Mobile.js : ui기준 mobile 설정 후 ui 화면 돋보이게 하기 위해 shadow효과 넣음
> 없음
=> setting:Global 설정 완료 / Global.js와 Mobile.js

cd-gq/src/App.js, cd-gq/src/index.js, cd-gq/src/pages/Sitemap.js, cd-gq/src/pages/main.js, cd-gq/src/styles/Mobile.js
- app.js / index.js / mobile.js 작업 진행 ➡️ ui 크기 설정 완료
> 좀 더 편한 작업을 위해 Main.js의 logo img에 <Link /> 사용하려고 했으나 사용하니 ui 설정이 다 깨져서 따로 빼놨습니다.
각 페이지별 플로우 이전으로 넘어가거나 다음으로 넘어가는 연결 있으면 좋을거 같아요~
=> feat/docs: mobile.js 설정하여 ui 크기 설정 완료

cd-gq/src/components/InputLocation.js, cd-gq/src/pages/main.js, cd-gq/src/styles/Mobile.js, cd-gq/src/styles/global.js, cd-gq/src/styles/theme.js
- InputLocation.js 컴포넌트 완성
- main.js / global.js / theme.js 수정
> 없음
- InputCrop.js에도 이번 작업 진행
=> docs/feat:InputLocation.js 완성.

cd-gq/src/components/DatePicker.js
-  pull받은 후 datepicker.js 오타 수정
> 없음
> 없음
- 확인하기 버튼 누르면 Home으로 넘어가는 라우팅 작업
- Detail페이지 백그라운드 작업
=> chore: pull받은 후 datepicker.js 오타 수정

cd-gq/src/components/InputCrop.js, cd-gq/src/components/InputDate.js, cd-gq/src/components/InputLocation.js, cd-gq/src/pages/main.js
- main.js 에서 height가 컴포넌트 변경되며 백그라운드가 짤리는 현상 해결
> 없음
https://github.com/CapstoneDesign24-GQ/FE/assets/118183190/5e0b71f2-a2ff-4e77-a10e-1bf886e1f7b1
- 확인하기 버튼 누르면 Home으로 넘어가는 라우팅 작업
- Detail페이지 백그라운드 작업
=> feat: main.js 에서 height가 컴포넌트 변경되며 백그라운드가 짤리는 현상 해결

cd-gq/src/components/DealWithPest.js, cd-gq/src/components/InputCrop.js, cd-gq/src/components/InputDate.js, cd-gq/src/components/InputLocation.js, cd-gq/src/components/PestContent.js, cd-gq/src/pages/Detail.js, cd-gq/src/styles/theme.js
- DealWithPest.js 컴포넌트 작업 진행
- 컴포넌트 안 toggle 요소들 자식 컴포넌트화 진
> onToggle 오류 발생. toggle onClick 이벤트 관련 오류임.
- page에서 height 관련 코드 작성 뒤 추가 작업할 예정
- 먼저 State.js component 작업 진행
=> design:DealWithPest.js component 작업 중. onToggle function error

cd-gq/src/pages/Detail.js
- 애벌레 위치 수정
> 없음
- home 페이지 백그라운드 작업
=> fix: 애벌레 위치 수정

cd-gq/src/components/Header.js, cd-gq/src/pages/Home.js
- Header.js Component ui 완성
- Header.js Component 기능 구현
- 해당 지역과 작물 클릭시 header의 지역, 작물 변경 구현 완료
> 변경하기 버튼을 추가하면서 디자인은 임의로 적용시켜놓았으니, 디자인 변경 원하시면 피그마에 변경부탁드립니다.
> 지역과 작물변경은 토글 대신 모달로 구현하였습니다.
https://github.com/CapstoneDesign24-GQ/FE/assets/118183190/e3fa5547-d9b5-4eb6-a2c8-bb13735853bf
- Home.js 백그라운드 설정
=> feat: Header.js Component ui 및 기능 구현

cd-gq/src/components/State.js, cd-gq/src/pages/Home.js, cd-gq/src/styles/theme.js
- width 다시 수정함
> 없음
- InputDate.js 달력 component 커스텀 중 color 오류 해결
=> design:State.js component width 수정 완료

cd-gq/src/components/InputCrop.js, cd-gq/src/components/InputLocation.js, cd-gq/src/components/State.js, cd-gq/src/pages/main.js
- Main page에서 input component들 백으로 쏴줄 dataForm 저장되는 코드를 localStorage에 저장되는 걸로 확인
- page 새로고침 시 dataForm 초기화 설정 완료
> 없음
- inputDate 수정 작업 진행
=> feat:Main page localStorage code inputDate 빼고 연동 완료

cd-gq/package-lock.json, cd-gq/package.json, cd-gq/src/components/PestInformation.js, cd-gq/src/components/Weather.js, cd-gq/src/pages/Home.js
- Weather.js UI구현
> 오른쪽 화살표는 아이콘 누르면 눌리는데 왼쪽 화살표 아이콘은 아이콘보다 왼쪽을 클릭해야 눌림..
https://github.com/CapstoneDesign24-GQ/FE/assets/118183190/e177c121-c56a-4d4a-b1a4-9a2c9ee4388f
- 기상청 api 연동
=> feat: Weather.js UI구현

cd-gq/src/components/Weather.js
- 풍속 이미지 잘못돼있어서 수정함
> 없음
> 없음
- 백 연동
=> chore: 풍속 이미지 수정

package-lock.json, package.json
- import vercel
> 없음
> 없음
- 다음 진행할 업무
=> setting(Vercel)

src/components/DealWithPest.js, src/components/InputDate.js, src/components/TestDownload.js, src/pages/Test1.js
- 엑셀 파일 다운로드 컴포넌트 구현(TestDownload.js) 
- 테스트용 코드 수정
> 파일명 중 포함된 파일 ID를 각 선택지에 따라 객체로 만든 뒤 링크 연결해야됨
> 파일 다운로드 눌렀을 때 토글 닫히는거 해결해야됨
- 토글 문제 해결
- JSON 파일 만들어서 BE api 연동 전까지 더미 데이터로 테스트 해보기
=> Setting file saver

src/components/DealWithPest.js
- toggle 열린 상태에서 다운로드 버튼 눌렀을 때 토글 안 닫히게 기능 구현
> 아..그...토글 컴포넌트 명 test에서 바꿔야되는데 깜빡함 히히.. 다음 커밋때 수정 반영할 예정
> 없음
- json 파일 생성 후 연결
=> feat:toggle Event setting

src/components/HomePage/State.js, src/db/State.json
- State component 아이콘, 색상 변경 완료
> 없음
> 없음
- 화살표에 이벤트 추가 작업 진행
- css 깨진 것 수정해야됨
=> feat(State-component):state.percent에 따라 색상,아이콘변경

src/components/HomePage/State.js
- State arrow event setting
- 
> 없음
> 없음
- api 연동
=> feat(State):Arrow event

src/components/DetailPage/DealWithPest.js, src/components/DetailPage/DownloadFile.js, src/db/file.json, src/pages/Detail.js
- 작업 사항 1
- 작업 사항 2
> 없음
> 없음
- 다음 진행할 업무
=> feat(download)

src/components/MainPage/InputCrop.js, src/components/MainPage/InputDate.js, src/components/MainPage/InputLocation.js
- Main InputComponent 들 중 버튼 active 상태 기능 구현
> 없음
> 없음
- api연동
=> Feat active

src/APIs/get/getStateInfo.js, src/APIs/put/putReCrop.js, src/APIs/put/putReLocation.js, src/components/HomePage/Header.js, src/components/HomePage/State.js, src/pages/Detail.js, src/pages/Home.js
- 작업 사항 1
- 작업 사항 2
> 없음
> 없음
- 다음 진행할 업무
=> feat: axios 중간커밋

src/APIs/get/getStateInfo.js, src/APIs/post/postMain.js, src/components/HomePage/State.js, src/pages/Home.js
- State 코드 대수정
- Home props 수정
> 없음
> 없음
- json 진행하기
=> Feat state3

src/APIs/post/postPestInfo.js, src/APIs/post/postSelect.js, src/pages/Detail.js, src/pages/main.js
- 작업 사항 1
- 작업 사항 2
> 없음
> 없음
- 다음 진행할 업무
=> feat: axios main구현

src/components/DetailPage/PestInformation.js, src/components/HomePage/Header.js, src/pages/Detail.js
- 작업 사항 1
- 작업 사항 2
> 없음
> 없음
- 다음 진행할 업무
=> detail페이지 api연동 중간 커밋

src/components/DetailPage/DealWithPest.js, src/components/DetailPage/PestInformation.js, src/pages/Detail.js
- 대처법에 해당해충으로 이름 바뀌게끔 함
> 없음
> 없음
- 다음 진행할 업무
=> fix: 대처법에 해당해충으로 이름 바뀌게끔 함

src/components/DetailPage/DealWithPest.js, src/components/DetailPage/DownloadFile.js, src/components/DetailPage/PestManagements.js
- DealWithPest component 부분에서 대처법 부분 component화 진행
- 대처법 component를 map함수 돌려 api 연동 개수에 맞게 출력되게 기능 구
> 없음
> 
- State.js 에서 State body 부분 양쪽 화살표 고정 시도해보기
=> Feat detail api

src/components/DetailPage/DealWithPest.js, src/components/DetailPage/PestManagements.js
- 대처법 숫자 나오게끔 구현
> 없음
- 다음 진행할 업무
=> feat: 대처법 숫자 나오게끔 구현

src/components/DetailPage/DealWithPest.js, src/components/DetailPage/Download.js, src/components/DetailPage/DownloadFile.js, src/components/MainPage/InputCrop.js
- 엑셀 다운로드 기능 오류 해결
- 농약 정보 api 구현 성공
> 없음
- 다음 진행할 업무
=> Feat download api

src/components/HomePage/Header.js, src/pages/Detail.js, src/routes.js
- 라우터 경로 수정
> 없음
> 없음
- 다음 진행할 업무
=> Edit router

src/pages/Home.js
: Home page api 연동 부분 수정 시도
- Home page에서 api 연동 코드 수정 시도
> 백엔드에서 이중 객체로 보내주는 데이터를 어떻게 해결해야될지 고민해봐야함
> 없음
- Home api 코드 다시 시도
=> docs(Home.js)

src/components/HomePage/State.js, src/pages/Home copy.js, src/pages/Home.js, src/routes.js
- 작업 사항 1
- 작업 사항 2
> 없음
> 없음
- 다음 진행할 업무
=> fix: state에서 임의로 설정해둔 초기값 출력 문제 해결완료

src/components/HomePage/State.js, src/pages/Home.js
- state 퍼센트 기준 수정
- state css 수정 및 작물변경시 state 리렌더링 되게끔 설정
> 없음
> 없음
- 다음 진행할 업무
=> fix: state css 수정 및 작물변경시 state 리렌더링 되게끔 설정

public/index.html
- 작업 사항 1
- 작업 사항 2
> 없음
> 없음
- 다음 진행할 업무
=> fix: vercel 오류 해결

build.sh
- 작업 사항 1
- 작업 사항 2
> 없음
> 없음
- 다음 진행할 업무
=> docs: build.sh파일 추가

workflows/deploy.yml
- 작업 사항 1
- 작업 사항 2
> 없음
> 없음
- 다음 진행할 업무
=> docs: deploy.yml파일 추가

src/pages/Test1.js
- 작업 사항 1
- 작업 사항 2
> 없음
> 없음
- 다음 진행할 업무
=> test: 깃허브 액션 배포 테스트

src/pages/Test1.js
- 작업 사항 1
- 작업 사항 2
> 없음
> 없음
- 다음 진행할 업무
=> test: 깃허브 액션 배포 테스트3

vercel.json
- 작업 사항 1
- 작업 사항 2
> 없음
> 없음
- 다음 진행할 업무
=> docs: vercel.json파일 추가

vercel.json
- 작업 사항 1
- 작업 사항 2
> 없음
> 없음
- 다음 진행할 업무
=> chore: vercel.json파일 수정

vercel.json
- 작업 사항 1
- 작업 사항 2
> 없음
> 없음
- 다음 진행할 업무
=> chore: vercel.json파일 수정2

vercel.json
- 작업 사항 1
- 작업 사항 2
> 없음
> 없음
- 다음 진행할 업무
=> chore: vercel.json파일 수정3

src/APIs/get/getStateInfo.js
- 작업 사항 1
- 작업 사항 2
> 없음
> 없음
- 다음 진행할 업무
=> fix: getStateInfo.js 수정
